$social=^(spotify|Spotify|vesktop)$

windowrule {
    name = social-media-rice
    match:class = $social
    workspace = 2, match:class ^(vesktop)$
    workspace = 4, match:class ^(spotify|Spotify)$
    opacity = 0.85 override 0.7 override
}