input {
    kb_layout = fr
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

input {
    kb_layout = fr
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
        tap-to-click = on
        disable_while_typing = on
    }
}

gestures {
# New 1:1 Workspace Swipe (Windows-style)
    gesture = 3, horizontal, workspace
    workspace_swipe_distance = 250 # Lower for faster switching, higher for more control
    workspace_swipe_invert = false  # Set to true if you want "Natural Scrolling" (content follows fingers)
workspace_swipe_forever = true
}