# --- Layer Rules (UI Elements) ---
layerrule = blur on, match:namespace ^(notifications|waybar)$
layerrule = ignore_alpha 0.5, match:namespace ^(notifications|waybar)$

# --- Global Window Defaults ---
windowrule {
    name = global-defaults
    match:class = .*
    opacity = 0.9 override 0.85 override
    no_blur = off
}

$ide=^(code-url-handler|code|jetbrains-idea|jetbrains-pycharm-ce)$
$browser=^(firefox|chromium|brave|vivaldi|microsoft-edge)$
$game=^(steam_app_\d+|dotnet|zenless|^Minecraft[\*\s\d.]*)$

# --- Development (IDEs) ---
windowrule {
    name = generic-ide
    match:class = $ide
    workspace = 3, match:class $ide
    opacity = 0.9 override 0.85 override
}

# --- Social & Media Rice ---
windowrule {
    name = social-media-rice
    match:class = ^(spotify|Spotify|vesktop)$
    workspace = 2, match:class ^(vesktop)$
    workspace = 4, match:class ^(spotify|Spotify)$~
    opacity = 0.9 override 0.85 override
}

# --- Opaque / Productivity Apps ---
windowrule {
    name = generic-opaque
    match:class = ^(xfreerdp|firefox)$
    workspace = 1, match:class ^(firefox)$
    workspace = 6, match:class ^(xfreerdp)$
    opacity = 1.0 override 1.0 override 1.0 override
    no_blur = on
    force_rgbx = on
    opaque = on
}

# --- Gaming (Steam & Proton) ---
windowrule {
    name = steam-client
    match:class = ^(steam)$
    workspace = 5
}

windowrule {
    name = games
    match:class = ^(steam_app_\d+|dotnet|zenless|^Minecraft[\*\s\d.]*)$
    workspace = 5, match:class ^(dotnet|zenless|^Minecraft[\*\s\d.]*)$
    opacity = 1 override 0.90 override
    fullscreen = on
    float = off
    decorate = off
}

windowrule {
    #media-ctl
    name = media-ctl
    match:class = ^(com.clement.mediactl|org.pulseaudio.pavucontrol)$
    float=on
    opacity = 0.8 override 0.7 override
    move= cursor_x-200 cursor_y+20 #spawn under cursorss
    size = 400 250
}