# --- Layer Rules (UI Elements) ---
layerrule = blur on, match:namespace ^(notifications|waybar)$
layerrule = ignore_alpha 0.5, match:namespace ^(notifications|waybar)$

# --- Global Window Defaults ---
windowrule {
    name = global-defaults
    match:class = .*
    opacity = 0.95 override 0.90 override
    no_blur = off
}

# --- Development (IDEs) ---
windowrule {
    name = generic-ide
    match:class = ^(code-url-handler|code|jetbrains-idea|jetbrains-pycharm-ce)$
    workspace = 3
    opacity = 0.95 override 0.90 override
}

# --- Social & Media Rice ---
windowrule {
    name = social-media-rice
    match:class = ^(spotify|Spotify|vesktop)$
    opacity = 0.90 override 0.80 override
}

# --- Opaque / Productivity Apps ---
windowrule {
    name = generic-opaque
    match:class = ^(xfreerdp|firefox)$
    workspace = 1, match:class ^(firefox)$
    opacity = 1.0 override 1.0 override 1.0 override
    no_blur = on
    force_rgbx = on
    opaque = on
}

# --- Gaming (Steam & Proton) ---
windowrule {
    name = steam-client
    match:class = ^(steam)$
    workspace = 5
}

windowrule {
    name = games
    match:class = ^(steam_app_\d+|dotnet|zenless|^Minecraft[\*\s\d.]*)$
    opacity = 1 override 0.90 override
    fullscreen = on
    float = off
    decorate = off
}