#!/usr/bin/env python3
"""css-bundle.py — flatten a CSS @import tree into one monolithic file.

Why: about:newtab / about:home apply a strict CSP that blocks @import'd
stylesheets, so textfox's config.css / content/newtab.css (and every --tf-*
var they define) never reach the newtab. Inlining every @import into a single
sheet leaves no imported sheets for the CSP to block — all rules apply directly.

Usage: css-bundle.py <entry.css> <output.css>

  - @import url("x.css") is replaced, in place, by x.css's (recursively
    bundled) contents. Order is preserved.
  - Paths resolve relative to the importing file (following symlinks, so the
    active/ overlay's config.css -> themes/<name>/textfox/config.css works).
  - Relative url(...) refs are rewritten relative to the OUTPUT location (the
    chrome/ root) so icon/asset paths keep resolving after the move.
  - Repeated imports of the same real file are emitted once (CSS @import would
    also de-dupe; this keeps the output lean).
"""
import os
import re
import sys

# @import url("path")  /  @import url(path) ;   (no media-query form is used here)
IMPORT_RE = re.compile(r'@import\s+url\(\s*(["\']?)([^"\')]+)\1\s*\)\s*;?')
# url( ... ) resource references
URL_RE = re.compile(r'url\(\s*(["\']?)([^"\')]+)\1\s*\)')

EXTERNAL_RE = re.compile(r'^\s*(data:|https?:|chrome:|resource:|moz-extension:|about:|/|#)')


def is_external(target: str) -> bool:
    return bool(EXTERNAL_RE.match(target))


def rewrite_urls(css: str, rel_dir: str) -> str:
    """Rewrite relative url(...) so they resolve from the output root.

    rel_dir is the source file's directory relative to the entry's directory
    (the chrome/ root after deploy). A ref at content/foo.css -> "x.svg"
    becomes "content/x.svg".
    """
    if not rel_dir:
        return css

    def repl(m: re.Match) -> str:
        quote, target = m.group(1), m.group(2)
        if is_external(target):
            return m.group(0)
        resolved = os.path.normpath(os.path.join(rel_dir, target))
        return f'url({quote}{resolved}{quote})'

    return URL_RE.sub(repl, css)


def bundle(path: str, seen: set, rel_dir: str) -> str:
    real = os.path.realpath(path)
    if real in seen:
        return f'/* css-bundle: skipped duplicate import {os.path.basename(path)} */\n'
    seen.add(real)

    with open(path, encoding='utf-8') as fh:
        css = fh.read()

    out = []
    last = 0
    src_dir = os.path.dirname(path)
    for m in IMPORT_RE.finditer(css):
        out.append(rewrite_urls(css[last:m.start()], rel_dir))
        target = m.group(2)
        if is_external(target):
            out.append(m.group(0))
        else:
            child = os.path.join(src_dir, target)
            child_rel = os.path.normpath(os.path.join(rel_dir, os.path.dirname(target)))
            if child_rel == '.':
                child_rel = ''
            if os.path.exists(child):
                out.append(bundle(child, seen, child_rel))
            else:
                out.append(f'/* css-bundle: MISSING import {target} */\n')
        last = m.end()
    out.append(rewrite_urls(css[last:], rel_dir))
    return ''.join(out)


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write('usage: css-bundle.py <entry.css> <output.css>\n')
        return 2
    entry, output = sys.argv[1], sys.argv[2]
    if not os.path.isfile(entry):
        sys.stderr.write(f'css-bundle: entry not found: {entry}\n')
        return 1
    result = bundle(entry, set(), '')
    header = f'/* GENERATED by css-bundle.py from {os.path.basename(entry)} — do not edit. */\n'
    # Never write through a symlink — that would clobber the repo source the
    # deployed file may still point at. Replace the link with a real file.
    if os.path.islink(output):
        os.unlink(output)
    with open(output, 'w', encoding='utf-8') as fh:
        fh.write(header + result)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
