# THEME: miyabi — kitty (Terafox), hexes sourced from Nightfox-Dark-Terafox

# The basic colors
foreground              #e6eaea
background              #152528
selection_foreground    #152528
selection_background    #2d4f56

# Cursor colors
cursor                  #73a3b7
cursor_text_color       #152528

# URL underline color
url_color               #91bccb

# Kitty window border colors
active_border_color     #4d9c9f
inactive_border_color   #233134
bell_border_color       #eb746b

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #152528
active_tab_background   #4d9c9f
inactive_tab_foreground #e6eaea
inactive_tab_background #233134
tab_bar_background      #0e191b

# Marks (highlighted text)
mark1_foreground #152528
mark1_background #73a3b7
mark2_foreground #152528
mark2_background #4d9c9f
mark3_foreground #152528
mark3_background #8eb2af

# The 16 terminal colors
# black
color0  #233134
color8  #3f585d
# red
color1  #eb746b
color9  #eb746b
# green
color2  #8eb2af
color10 #8eb2af
# yellow
color3  #fdb292
color11 #ff9664
# blue
color4  #73a3b7
color12 #91bccb
# magenta
color5  #ce8cd7
color13 #ce8cd7
# cyan
color6  #95b9c8
color14 #91bccb
# white
color7  #e6eaea
color15 #f6f2ee

background_opacity 0.85
