# THEME: Miyabi Light — liquid glass

foreground              #163047
background              #edf5f8
selection_foreground    #edf5f8
selection_background    #2f91a9

cursor                  #23758f
cursor_text_color       #edf5f8
url_color               #23758f

active_border_color     #2f91a9
inactive_border_color   #b7d3dc
bell_border_color       #c65a64

wayland_titlebar_color  system
macos_titlebar_color    system

active_tab_foreground   #163047
active_tab_background   #d8eef3
inactive_tab_foreground #5e7885
inactive_tab_background #f8fcff
tab_bar_background      #dceff4

mark1_foreground        #edf5f8
mark1_background        #23758f
mark2_foreground        #edf5f8
mark2_background        #2f91a9
mark3_foreground        #163047
mark3_background        #d6a85b

# ANSI colors
color0  #294754
color8  #426676
color1  #a33d4a
color9  #be4d5a
color2  #26724f
color10 #35885f
color3  #7b5c1b
color11 #9b741b
color4  #225b91
color12 #2d73b4
color5  #7d4a82
color13 #984f9f
color6  #176f7b
color14 #258d9c
color7  #426676
color15 #163047

background_opacity 1.0
